##print ( "Hello world" )
##print ( "이샘", "코딩", "전문", "학원")
##print ( "코딩세계에", "오신걸", "환영합니다" )
##print("이샘", "학원",sep="코딩전문")
##print("이샘코딩학원",end="!!")
##print("안녕하세요\n")
##print("안녕하세요\n")
##print('안녕하세요',end="")
##print("안녕하세요",end='')
##print("\", \'는 따옴표의 대체 기호입니다.")
##print("\\n은 줄바꿈의 대체 기호입니다.")
##print("따옴표는 '역할'이 같아요")
##print('따옴표는 "역할"이 같아요')
##print('따옴표는 "역할"이 같아요')
##print("따옴표는 '역할'이 같아요")
##apple = "사과"
##print(apple, 1, "상자",sep="=")
##print("이샘")
##print("코딩")
##print("학원")
##print("이샘",end="")
##print("코딩",end="!")
##print("학원",end="!")
##num1 = 10
##print(num1, type(num1))
##num2 =3.14
##print(num2, type(num2))
##kanil = "안녕하세요"
##print(kanil, type(kanil))
##print(1+1, type(1.1+1))
##print('"이샘코딩학원"\n')
##print(1,2,3,sep="+",end="=6")
##num1=17
##print(num1)
##print("10진수 17 = %d"%(num1))
##print("10진수 17의 8진수 = %o"%(num1))
##print("10진수 17의 16진수 = %x"%(num1))
##num2 =97
##print("%d %c" % (num2,num2))
##float1=1234.567
##print(float1)
##print("기본 출력 %f" % (float1))
##print("지수표기법 %e" % (float1))
##print("소수 둘째자리까지 %.2f" % (float1))
