##print ( "Hollo world" )
##print ( "이샘" , "코딩" , "전문" , "학원" )
##print ( "코딩세계에" , "오신걸" , "환영합니다" )
##print ( "이샘", "학원" , "코딩전문",sep=',' )
##print ( "이샘코딩학원" ,end="!!" )
##print ( "안녕하세요" )
##print ( "안녕하세요" )
##print ( "안녕하세요\n" )
##print ( "안녕하세요\n" )
##print ( '안녕하세요' ,end="")
##print ( "안녕하세요" ,end='')
##print ("\",\"는 따옴표의 대체 기호입니다.")
##print ("\\n은 줄바꿈의 대체 기호입니다.")
##print ( "따옴표는 '역할'이 같아요")
##print ( '따옴표는 "역할"이 같아요')
##print ( '따옴표는 "역할" 같아요.' )
##print ( "따옴표는 '역할 같아요." )
##apple = "사과"
##print(apple, 1, "상자", sep="++" )
##apple = "사과"
##print(apple, 1, "상자")
##print( "안녕하세요 저는 박강일 입니다 ㅎㅎ" )
##print("이샘")
##print("코딩")
##print("학원")
print("이샘" ,end="")
print("코딩" ,end="")
print("학원" ,end="")
